{% set name = "fastjet" %}
{% set version = "3.4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastjet-{{ version }}.tar.gz
  sha256: 5f3897cdd22a55dee96edcd54898bcfbe21cdacfa93c15269780a97229e9c2bc
  patches:
    - 0001-Don-t-overwrite-external-CXXFLAGS-and-LDFLAGS.patch
    - 0002-Patch-fastjet-contrib-Makefile.in.patch

build:
  number: 0
  skip: true  # [not linux]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - autoconf
    - automake
    - libtool
    - make
    - patch
    - swig
  host:
    - cgal-cpp  # headers and CGALv5
    - gmp  # shared library
    - pip
    - pybind11
    - python
    - setuptools_scm  # required for 'python -m build'
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector

test:
  imports:
    - fastjet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/fastjet
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
    - matthewfeickert
