{% set name = "fastjet" %}
{% set version = "3.4.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastjet-{{ version }}.tar.gz
  sha256: 4b5d8051fd374514159ff89b69ab0c4da7b3b757c257f82593fc176e3bb0c4be
  patches:
    - 0001-Don-t-overwrite-external-CXXFLAGS-and-LDFLAGS.patch
    - 0002-Patch-fastjet-contrib-Makefile.in.patch

build:
  number: 0
  skip: true  # [not linux]
  script:
    # Use 'python -m build' to build a wheel first to avoid having the overlinking
    # check fail by looking in the wrong CPython build_artifacts directory.
    # It is unclear if this is something that conda-forge should know how to avoid
    # or if this could be fixed by improvements in the fastjet build system.
    - {{ PYTHON }} -m build --no-isolation .
    - {{ PYTHON }} -m pip install --verbose --verbose ./dist/fastjet-*.whl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - make
    - patch
    - swig
  host:
    - python-build  # see comment in build script section
    - cgal-cpp  # headers and CGALv5
    - gmp  # shared library
    - pip
    - pybind11
    - python
    - setuptools_scm  # required for 'python -m build'
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector

test:
  imports:
    - fastjet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/fastjet
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
    - matthewfeickert
