schema_version: 1

context:
  name: fastjet
  version: "3.5.2.0"
  # pinned fastjet_cxx version is always the 3 highest version numbers of fastjet
  fastjet_cxx_version: ${{ ((version | split('.') | list)[:3] | join('.')) }}
  # check alignment with https://github.com/scikit-hep/fastjet and https://github.com/cms-externals/fastjet-contrib
  fastjet_contrib_version: "1.105"

package:
  name: fastjet
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastjet/fastjet-${{ version }}.tar.gz
  sha256: 4f01dcf8c42031efe680d74d4a3d0c2301d99c46dbea21d81d9b8006865b81b7

build:
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation -C"cmake.define.SKHEPFJ_USE_INSTALLED_FASTJET=ON" -C"cmake.define.SKHEPFJ_USE_INSTALLED_FASTJET_CONTRIB=ON" -C"cmake.define.SKHEPFJ_PASSTHRU_FASTJET_SWIG=ON"

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - cmake
    - if: unix
      then: make
  host:
    - fastjet-cxx ==${{ fastjet_cxx_version }} # pick up global pinning
    - fastjet-cxx-devel ==${{ fastjet_cxx_version }}
    - fastjet-cxx-python ==${{ fastjet_cxx_version }}
    - fastjet-contrib ==${{ fastjet_contrib_version }} # pick up global pinning
    - fastjet-contrib-devel ==${{ fastjet_contrib_version }}
    - pip
    - scikit-build-core
    - setuptools_scm
    - pybind11
    - python
    - if: not (win and arm64)
      then: cgal-cpp
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector
    - fastjet-cxx-python ==${{ fastjet_cxx_version }}

tests:
  - package_contents:
      files:
        - if: win
          # py3.15 moved Windows site-packages to lib/python/site-packages (as in conda-forge/fastjet-cxx-feedstock#29)
          then: "{Lib,lib/python}/site-packages/fastjet/_ext.*"
          else: lib/python*/site-packages/fastjet/_ext.*
      site_packages:
        - fastjet
        - fastjet._generalevent
        - fastjet._multievent
        - fastjet._pyjet
        - fastjet._singleevent
        - fastjet._swig
        - fastjet._utils
        - fastjet.version
  - python:
      imports:
        - fastjet
      pip_check: true
  - requirements:
      run:
        - pip
        - python
    script:
      - pip list

about:
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/fastjet

extra:
  recipe-maintainers:
    - kratsg
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
    - matthewfeickert
