schema_version: 1

context:
  name: fastjet
  version: "3.5.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastjet-${{ version }}.tar.gz
  sha256: 2a1d6762d3e9861b1d38f0e6d08871b60369bb87201ea423968f6eacc0851e3f
  patches:
    - 0001-patches-to-use-conda-dependencies.patch

build:
  number: 0
  skip: win
  script:
    - ${{ PYTHON }} -m pip install . -vv -C"cmake.define.SKHEPFJ_USE_INSTALLED_FASTJET=ON" -C"cmake.define.SKHEPFJ_USE_INSTALLED_FASTJET_CONTRIB=ON" -C"cmake.define.SKHEPFJ_FASTJET_CXX_SWIG=ON"

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - fastjet-cxx-python
        - fastjet-contrib
    - cmake
    - if: unix
      then: make
    - swig
    - cgal
  host:
    - fastjet-cxx-python
    - fastjet-contrib
    - pip
    - scikit-build-core
    - setuptools_scm
    - pybind11
    - python
  run:
    - awkward >=2
    - numpy >=1.13.3,<2.3
    - python
    - vector
    - fastjet-cxx-python
    - fastjet-contrib

tests:
  - python:
      imports:
        - fastjet
      pip_check: true
  - requirements:
      run:
        - pip
        - python
    script:
      - pip list

about:
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/fastjet

extra:
  recipe-maintainers:
    - kratsg
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
    - matthewfeickert
