schema_version: 1

context:
  name: fastjet
  version: 3.4.0.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/fastjet-${{ version }}.tar.gz
  sha256: 86dea05ce7a030db9fe14e5bf1c0bc46351b6e439f9b9ef6b14a55ceefcc7b7a
  patches:
    - 0001-Don-t-overwrite-external-CXXFLAGS-and-LDFLAGS.patch
    - 0002-Patch-fastjet-contrib-Makefile.in.patch

build:
  number: 9
  skip: not linux
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - autoconf
    - automake
    - libtool
    - make
    - patch
    - swig
  host:
    - cgal-cpp  # headers and CGALv5
    - gmp  # shared library
    - pip
    - pybind11
    - python
    - setuptools_scm  # required for 'python -m build'
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector

tests:
  - python:
      imports:
        - fastjet
      pip_check: true
  - requirements:
      run:
        - pip
        - python
    script:
      - pip list

about:
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/fastjet

extra:
  recipe-maintainers:
    - kratsg
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
    - matthewfeickert
